version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - aliceblue
  - ANSIREGEX
  - antiquewhite
  - astro
  - bithound
  - blanchedalmond
  - blueviolet
  - buildable
  - burlywood
  - cadetblue
  - caseta
  - cbar
  - Chrono
  - codeowners
  - codez
  - cornflowerblue
  - cornsilk
  - creationrc
  - darkcyan
  - darkgoldenrod
  - darkgray
  - darkgreen
  - quicktype
  - darkgrey
  - darkkhaki
  - hvac
  - darkmagenta
  - darkolivegreen
  - darkorange
  - darkorchid
  - darkred
  - darksalmon
  - darkseagreen
  - darkslateblue
  - darkslategray
  - darkslategrey
  - darkturquoise
  - darkviolet
  - datetime
  - dbaeumer
  - deeppink
  - deepskyblue
  - devkit
  - dhall
  - dimgray
  - dimgrey
  - dodgerblue
  - entites
  - esbenp
  - execa
  - exiasr
  - falsey
  - fastify
  - floralwhite
  - fontawesome
  - forestgreen
  - fuzzysort
  - gainsboro
  - gbit
  - ghostwhite
  - gotify
  - greenyellow
  - gridsome
  - hadolint
  - hass
  - hassio
  - hmss
  - homeassistant
  - hotpink
  - idris
  - indianred
  - intellij
  - interwebs
  - julianday
  - kbit
  - keyfile
  - keylist
  - keymap
  - Keymaps
  - keypresses
  - kusto
  - lavenderblush
  - lawngreen
  - lemonchiffon
  - lifecycles
  - lightcoral
  - lightcyan
  - lightgoldenrodyellow
  - lightgray
  - lightgreen
  - lightpink
  - lightsalmon
  - lightseagreen
  - lightskyblue
  - lightslategray
  - lightslategrey
  - lightsteelblue
  - lightyellow
  - limegreen
  - lutron
  - managerrc
  - maxage
  - mbar
  - mbit
  - mediumaquamarine
  - mediumblue
  - mediumorchid
  - mediumpurple
  - mediumseagreen
  - mediumslateblue
  - mediumspringgreen
  - mediumturquoise
  - mediumvioletred
  - midnightblue
  - milli
  - mintcream
  - mireds
  - mistyrose
  - mrad
  - navajowhite
  - navyblue
  - nocheck
  - npmjs
  - nrwl
  - nsoult
  - numlen
  - nxignore
  - oldlace
  - olivedrab
  - orangered
  - pagedown
  - pageup
  - pagga
  - palegoldenrod
  - palegreen
  - paleturquoise
  - palevioletred
  - papayawhip
  - peachpuff
  - pico
  - pino
  - pkief
  - postdata
  - powderblue
  - prettyrc
  - proto
  - purescript
  - reftimes
  - rgbw
  - rgbww
  - rosybrown
  - royalblue
  - rrule
  - saddlebrown
  - sandybrown
  - seagreen
  - searchbox
  - shellcheck
  - sinm
  - sinonjs
  - skyblue
  - slateblue
  - slategray
  - slategrey
  - snapse
  - sonarjs
  - springgreen
  - steelblue
  - terminalizer
  - testrc
  - timonwong
  - toolbelt
  - tput
  - tsdoc
  - typeof
  - undici
  - unitless
  - unpublish
  - UNSORTABLE
  - visbility
  - vsix
  - whitesmoke
  - womp
  - writerrc
  - yellowgreen
  - zipignore
ignoreWords: []
import: []
